# 2024 jmfariasdev (João Marcos Farias)
# §§=> Alacritty <=§§ configuration file.

[shell]
program = '/usr/bin/bash'

[window]
dimensions = { columns = 120, lines = 28 }
padding = { x = 10, y = 5 }
decorations = 'None'
opacity = 0.92

[scrolling]
multiplier = 2

[font]
size = 11.5

[font.normal]
family = 'JetbrainsMono Nerd Font Mono'
style = 'Regular'

[selection]
save_to_clipboard = true

[cursor]
thickness = 0.1

[mouse]
hide_when_typing = true

[colors]
transparent_background_colors = true

# TokyoNight Alacritty Colors
[colors.primary]
background = '#1a1b26'
foreground = '#c0caf5'

[colors.cursor]
cursor = '#c0caf5'
text = '#1a1b26'

# Normal colors
[colors.normal]
black = '#15161e'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

# Bright colors
[colors.bright]
black = '#414868'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#c0caf5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff9e64'

[[colors.indexed_colors]]
index = 17
color = '#db4b4b'
